sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: 
deploy:
  app: young-brook-85121
  provider: heroku
  api_key:
    secure: $KEY
env:
  global:
    secure: zXv4EIAf4azYuiocdPc5kmzQBS0rCeOQXLjOvE+zYO4GW2e5KEBrfolwZ0ckUyRA8KS+ObXH+TdVtAiwFYT1qfW8p+kXq7dHlITQywsbSHHFAQEFGER4pWlMyNdtEC3Ez/EPDZJqVaoN4lwwrCPmOdwNKa9Wb0fX+x5tOhUhblQ8XfW+AXXoL1XrotZe4Eua29k59C4EfJXPcWd8kQOpbtAT/QjF21AV5p+/pZM6XH9WxLZw/ZH0EekTjGcwGsWOZV7Rzu7sP23Ei+NOdaBvMcHrbGQAYVvzMwZM6OpPZKiz9SBo4Z+B/w7yDgmBNgPNVEFUEVEgxnJjOW0OrekoeN5q5k1gc5Np5W2tC1QTe9X6nEWJ2y3lvbnUKQr2eXo6r4iCga4BpQJ2yncZwlFh9X+WDJKxKfghGyyn0rcAWl32zJiH7Tr5s2szfOqCsTtsKyyNLxSvZQuRvV2ZbMNXMwdhThkwnJO4vbgi+eHAhbevz6KYxjLdkk1t2ra4g7I+iBSfmPnRDp9XKU4/5t7cYB2XBpky+3hgw0fXpPoKoSlj5fDVHU+J8wGBXUCxRv9emONXkZJp5DmixvOvc9y4uJAv/cxuTL+lZcl27YP38Gd8O7+i9kDYk+cN1zhKygTw6UuLBPsa61oIXe501lOj4NESca+PqPNzknRZnT1oyXw=
